### ISSUE TITLE
Color temp vs white value

### ISSUE THREAD

**Issue by jjensn** [mxtra/yeelight-ha#5]
Last issue for today, I swear.

I see back in September you were able to get white values merged into the master branch: https://github.com/home-assistant/home-assistant/pull/3338

@martinhjelmare says:

> [..]others control RGB separately from W. To be able to control only the W channel and support all device types, we need a parameter for White that is separate from Brightness.

This sounds like the Yeelight bulb: mixed RGB and White.

I can work on moving this over to White color instead of Color temperature -- is there a reason you wanted to implement white as a color temp instead of a white color?

**Comment by mxtra** [comment]
No problem, any help is welcome. :) The real problem however is, that there seems to be no way provided to change RGB and white channels independently. But the Yeelight API does provides a method for changimg the color temp directly - so that's why im using it. Some devices on the other hand allow you to set all four channels yourself while our Yeelights sets the white value automatically based on the RgB values according to my observations.
